
version: '3.0'

services:
  # guacd
  guacd:
    image: guacamole/guacd
    restart: unless-stopped
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  # postgres
  init-guacamole-db:
    image: guacamole/guacamole:latest
    command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
    volumes:
      - dbinit:/init


  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: guacamole_team5
      POSTGRES_USER: guacamole_user
    image: postgres
    restart: unless-stopped
    volumes:
      - dbinit:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
#    - ./init:/docker-entrypoint-initdb.d:ro
#    - ./data:/var/lib/postgresql/data:rw
    depends_on:
      - init-guacamole-db

  # guacamole
  guacamole:
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: guacamole_team5
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
      - guacd
    ports:
## enable next line if not using nginx
#    - 8080:8080/tcp
      - "8080:8080"
## enable next line when using nginx
#    - 8080/tcp
    restart: always

  apache-setup:
    image: guacamole/guacamole
    volumes:
      - "./tomcat-setup.sh:/usr/local/bin/apache2-custom.sh"
    command:
      - apache2-custom.sh
    depends_on:
      - guacamole
      - postgres
      - guacd

volumes:
  dbinit:
    driver: local
  dbdata:
    driver: local

#
#  apache:
#    restart: always
#    image: 'bitnami/tomcat:9.0'
#    ports:
#      - '8080:8080'
#    volumes:
#      - 'tomcat_data:/bitnami'
#    links:
#      - guacamole
##    command: /bin/bash -c tomcat-setup.sh
#
#
#volumes:
#  tomcat_data:
#    driver: local